services:
  # Backend API service
  - type: web
    name: zerotoinfinity-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn takeyouforward.wsgi:application
    envVars:
      - key: DEBUG
        value: false
      - key: ALLOWED_HOSTS
        value: "zerotoinfinity-api.onrender.com,*.onrender.com"
      - key: CORS_ALLOWED_ORIGINS
        value: "https://zerotoinfinity.vercel.app"
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: zerotoinfinity-db
          property: connectionString

databases:
  - name: zerotoinfinity-db
    databaseName: zerotoinfinity
    user: zerotoinfinity_user
